import {
  ConversationStatus,
  CustomerStatus,
  OrderStatus,
  ProductStatus,
  WhatsAppInstanceStatus,
} from '../types'

export const STATUS_LABELS: Record<string, string> = {
  [ConversationStatus.Open]: 'Aberta',
  [ConversationStatus.Pending]: 'Pendente',
  [ConversationStatus.Assigned]: 'Atribuída',
  [ConversationStatus.Paused]: 'Bot pausado',
  [ConversationStatus.Closed]: 'Encerrada',
  [ConversationStatus.Escalated]: 'Escalada',
  [OrderStatus.Draft]: 'Rascunho',
  [OrderStatus.Confirmed]: 'Confirmado',
  [OrderStatus.Processing]: 'Em preparo',
  [OrderStatus.Shipped]: 'Enviado',
  [OrderStatus.Delivered]: 'Entregue',
  [OrderStatus.Cancelled]: 'Cancelado',
  [ProductStatus.Active]: 'Ativo',
  [ProductStatus.Inactive]: 'Inativo',
  [ProductStatus.OutOfStock]: 'Sem estoque',
  [CustomerStatus.Blocked]: 'Bloqueado',
  [CustomerStatus.Vip]: 'VIP',
  [WhatsAppInstanceStatus.Connected]: 'Conectado',
  [WhatsAppInstanceStatus.Disconnected]: 'Desconectado',
  [WhatsAppInstanceStatus.Connecting]: 'Conectando',
  [WhatsAppInstanceStatus.Error]: 'Erro',
}

export const STATUS_COLORS: Record<string, string> = {
  [ConversationStatus.Open]: 'bg-emerald-100 text-emerald-700',
  [ConversationStatus.Pending]: 'bg-amber-100 text-amber-700',
  [ConversationStatus.Assigned]: 'bg-indigo-100 text-indigo-700',
  [ConversationStatus.Paused]: 'bg-slate-200 text-slate-700',
  [ConversationStatus.Closed]: 'bg-slate-100 text-slate-600',
  [ConversationStatus.Escalated]: 'bg-rose-100 text-rose-700',
  [OrderStatus.Draft]: 'bg-slate-100 text-slate-700',
  [OrderStatus.Confirmed]: 'bg-sky-100 text-sky-700',
  [OrderStatus.Processing]: 'bg-indigo-100 text-indigo-700',
  [OrderStatus.Shipped]: 'bg-violet-100 text-violet-700',
  [OrderStatus.Delivered]: 'bg-emerald-100 text-emerald-700',
  [OrderStatus.Cancelled]: 'bg-rose-100 text-rose-700',
  [ProductStatus.Active]: 'bg-emerald-100 text-emerald-700',
  [ProductStatus.Inactive]: 'bg-slate-100 text-slate-700',
  [ProductStatus.OutOfStock]: 'bg-rose-100 text-rose-700',
  [CustomerStatus.Blocked]: 'bg-rose-100 text-rose-700',
  [CustomerStatus.Vip]: 'bg-amber-100 text-amber-700',
  [WhatsAppInstanceStatus.Connected]: 'bg-emerald-100 text-emerald-700',
  [WhatsAppInstanceStatus.Disconnected]: 'bg-slate-100 text-slate-700',
  [WhatsAppInstanceStatus.Connecting]: 'bg-sky-100 text-sky-700',
  [WhatsAppInstanceStatus.Error]: 'bg-rose-100 text-rose-700',
}
